### ISSUE TITLE
check what's the fastest connection/frame extraction method

### ISSUE THREAD

**Issue by flavioribeiro** [cbsinteractive/hawkeye#1]
try and compare RTMP versus RTP connection to verify how long it takes to estabilish the connection and extract a frame. If we want this to be effective, we need to be able to extract multiple frames per second.

* Should we also do a connect/extract frame/disconnect loop or keep a stateful connection?

**Comment by rafaelcaricio** [comment]
Currently, we can fully process about 8 frames per second. I think we can close this ticket.
