### ISSUE TITLE
Ignore action if Watcher is already stopped/running

### ISSUE THREAD

**Issue by rafaelcaricio** [cbsinteractive/hawkeye#29]
Clients might request the Watcher to be set to running or stopped when they are already in that state. Currently, we are returning 409 Conflict HTTP code. Ideally, we would acknowledge it is already in that state and return 200 HTTP code.

We need to change the lines:
https://github.com/cbsinteractive/hawkeye/blob/85430382034d3eae1999941eb7ee8fb2e74bf736/hawkeye-api/src/handlers.rs#L262

https://github.com/cbsinteractive/hawkeye/blob/85430382034d3eae1999941eb7ee8fb2e74bf736/hawkeye-api/src/handlers.rs#L345

To return `StatusCode::OK`

**Comment by sarahnagata-viacomcbs** [comment]
@rafaelcaricio when you get a chance, can you change the milestone on this to be Sprint 14?  I did not have permissions to apply the milestone during the planning meeting. Thanks!
